#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x71C636695B147849 (dict-upload@aspell.net)
#
Name     : aspell-en
Version  : 2020.12.07.0
Release  : 13
URL      : https://mirrors.kernel.org/gnu/aspell/dict/en/aspell6-en-2020.12.07-0.tar.bz2
Source0  : https://mirrors.kernel.org/gnu/aspell/dict/en/aspell6-en-2020.12.07-0.tar.bz2
Source1  : https://mirrors.kernel.org/gnu/aspell/dict/en/aspell6-en-2020.12.07-0.tar.bz2.sig
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause BSD-4-Clause HPND Public-Domain
Requires: aspell-en-license = %{version}-%{release}
BuildRequires : aspell
Patch1: 0001-Allow-unrecognized-options.patch

%description
GNU Aspell 0.60 English Dictionary Package
Version 2020.12.07-0
2020-12-07
Original Word List By:
Kevin Atkinson <kevina at gnu org>
Wordlist URL: http://wordlist.aspell.net/
Source Version: 2020.12.07
This word list is considered both complete and accurate.

%package license
Summary: license components for the aspell-en package.
Group: Default

%description license
license components for the aspell-en package.


%prep
%setup -q -n aspell6-en-2020.12.07-0
cd %{_builddir}/aspell6-en-2020.12.07-0
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1607397689
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%configure --disable-static
make  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1607397689
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/aspell-en
cp %{_builddir}/aspell6-en-2020.12.07-0/Copyright %{buildroot}/usr/share/package-licenses/aspell-en/26bebd06268ce5071af116624daf2a4df0ff6c0b
%make_install

%files
%defattr(-,root,root,-)
/usr/lib64/aspell-0.60/american-variant_0.alias
/usr/lib64/aspell-0.60/american-variant_1.alias
/usr/lib64/aspell-0.60/american-w_accents.alias
/usr/lib64/aspell-0.60/american-wo_accents.alias
/usr/lib64/aspell-0.60/american.alias
/usr/lib64/aspell-0.60/australian-variant_0.alias
/usr/lib64/aspell-0.60/australian-variant_1.alias
/usr/lib64/aspell-0.60/australian-w_accents.alias
/usr/lib64/aspell-0.60/australian-wo_accents.alias
/usr/lib64/aspell-0.60/australian.alias
/usr/lib64/aspell-0.60/british-ise-w_accents.alias
/usr/lib64/aspell-0.60/british-ise-wo_accents.alias
/usr/lib64/aspell-0.60/british-ise.alias
/usr/lib64/aspell-0.60/british-ize-w_accents.alias
/usr/lib64/aspell-0.60/british-ize-wo_accents.alias
/usr/lib64/aspell-0.60/british-ize.alias
/usr/lib64/aspell-0.60/british-variant_0.alias
/usr/lib64/aspell-0.60/british-variant_1.alias
/usr/lib64/aspell-0.60/british-w_accents.alias
/usr/lib64/aspell-0.60/british-wo_accents.alias
/usr/lib64/aspell-0.60/british.alias
/usr/lib64/aspell-0.60/canadian-variant_0.alias
/usr/lib64/aspell-0.60/canadian-variant_1.alias
/usr/lib64/aspell-0.60/canadian-w_accents.alias
/usr/lib64/aspell-0.60/canadian-wo_accents.alias
/usr/lib64/aspell-0.60/canadian.alias
/usr/lib64/aspell-0.60/en-common.rws
/usr/lib64/aspell-0.60/en-variant_0.multi
/usr/lib64/aspell-0.60/en-variant_0.rws
/usr/lib64/aspell-0.60/en-variant_1.multi
/usr/lib64/aspell-0.60/en-variant_1.rws
/usr/lib64/aspell-0.60/en-variant_2.multi
/usr/lib64/aspell-0.60/en-variant_2.rws
/usr/lib64/aspell-0.60/en-w_accents-only.rws
/usr/lib64/aspell-0.60/en-w_accents.multi
/usr/lib64/aspell-0.60/en-wo_accents-only.rws
/usr/lib64/aspell-0.60/en-wo_accents.multi
/usr/lib64/aspell-0.60/en.dat
/usr/lib64/aspell-0.60/en.multi
/usr/lib64/aspell-0.60/en_AU-variant_0.multi
/usr/lib64/aspell-0.60/en_AU-variant_0.rws
/usr/lib64/aspell-0.60/en_AU-variant_1.multi
/usr/lib64/aspell-0.60/en_AU-variant_1.rws
/usr/lib64/aspell-0.60/en_AU-w_accents-only.rws
/usr/lib64/aspell-0.60/en_AU-w_accents.multi
/usr/lib64/aspell-0.60/en_AU-wo_accents-only.rws
/usr/lib64/aspell-0.60/en_AU-wo_accents.multi
/usr/lib64/aspell-0.60/en_AU.multi
/usr/lib64/aspell-0.60/en_CA-variant_0.multi
/usr/lib64/aspell-0.60/en_CA-variant_0.rws
/usr/lib64/aspell-0.60/en_CA-variant_1.multi
/usr/lib64/aspell-0.60/en_CA-variant_1.rws
/usr/lib64/aspell-0.60/en_CA-w_accents-only.rws
/usr/lib64/aspell-0.60/en_CA-w_accents.multi
/usr/lib64/aspell-0.60/en_CA-wo_accents-only.rws
/usr/lib64/aspell-0.60/en_CA-wo_accents.multi
/usr/lib64/aspell-0.60/en_CA.multi
/usr/lib64/aspell-0.60/en_GB-ise-w_accents-only.rws
/usr/lib64/aspell-0.60/en_GB-ise-w_accents.multi
/usr/lib64/aspell-0.60/en_GB-ise-wo_accents-only.rws
/usr/lib64/aspell-0.60/en_GB-ise-wo_accents.multi
/usr/lib64/aspell-0.60/en_GB-ise.multi
/usr/lib64/aspell-0.60/en_GB-ize-w_accents-only.rws
/usr/lib64/aspell-0.60/en_GB-ize-w_accents.multi
/usr/lib64/aspell-0.60/en_GB-ize-wo_accents-only.rws
/usr/lib64/aspell-0.60/en_GB-ize-wo_accents.multi
/usr/lib64/aspell-0.60/en_GB-ize.multi
/usr/lib64/aspell-0.60/en_GB-variant_0.multi
/usr/lib64/aspell-0.60/en_GB-variant_0.rws
/usr/lib64/aspell-0.60/en_GB-variant_1.multi
/usr/lib64/aspell-0.60/en_GB-variant_1.rws
/usr/lib64/aspell-0.60/en_GB-w_accents.multi
/usr/lib64/aspell-0.60/en_GB-wo_accents.multi
/usr/lib64/aspell-0.60/en_GB.multi
/usr/lib64/aspell-0.60/en_US-variant_0.multi
/usr/lib64/aspell-0.60/en_US-variant_1.multi
/usr/lib64/aspell-0.60/en_US-w_accents-only.rws
/usr/lib64/aspell-0.60/en_US-w_accents.multi
/usr/lib64/aspell-0.60/en_US-wo_accents-only.rws
/usr/lib64/aspell-0.60/en_US-wo_accents.multi
/usr/lib64/aspell-0.60/en_US.multi
/usr/lib64/aspell-0.60/en_affix.dat
/usr/lib64/aspell-0.60/en_phonet.dat
/usr/lib64/aspell-0.60/english-variant_0.alias
/usr/lib64/aspell-0.60/english-variant_1.alias
/usr/lib64/aspell-0.60/english-variant_2.alias
/usr/lib64/aspell-0.60/english-w_accents.alias
/usr/lib64/aspell-0.60/english-wo_accents.alias
/usr/lib64/aspell-0.60/english.alias

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/aspell-en/26bebd06268ce5071af116624daf2a4df0ff6c0b
